In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df=pd.read_csv('/content/Social_Network_Ads.csv')
df.shape

(400, 5)

In [21]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [22]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [24]:
df=df.drop(columns=['User ID'])
df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
display(df.head())

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [26]:
df.corr().loc["Purchased"]

Gender            -0.042469
Age                0.622454
EstimatedSalary    0.362083
Purchased          1.000000
Name: Purchased, dtype: float64

In [27]:
X = df.drop('Purchased', axis=1)
y = df['Purchased']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (400, 3)
Shape of y: (400,)


In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (280, 3)
Shape of X_test: (120, 3)
Shape of y_train: (280,)
Shape of y_test: (120,)


In [29]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

scaler = StandardScaler()

# Columns to scale
columns_to_scale = ['Age', 'EstimatedSalary']

# Apply scaler to X_train
X_train_scaled_numeric = scaler.fit_transform(X_train[columns_to_scale])
X_train_scaled_df = pd.DataFrame(X_train_scaled_numeric, columns=columns_to_scale, index=X_train.index)
X_train_scaled = pd.concat([X_train[['Gender']], X_train_scaled_df], axis=1)

# Apply scaler to X_test
X_test_scaled_numeric = scaler.transform(X_test[columns_to_scale])
X_test_scaled_df = pd.DataFrame(X_test_scaled_numeric, columns=columns_to_scale, index=X_test.index)
X_test_scaled = pd.concat([X_test[['Gender']], X_test_scaled_df], axis=1)

print("Shape of X_train_scaled:", X_train_scaled.shape)
print("Shape of X_test_scaled:", X_test_scaled.shape)

print("\nX_train_scaled (first 5 rows):")
display(X_train_scaled.head())

print("\nX_test_scaled (first 5 rows):")
display(X_test_scaled.head())

Shape of X_train_scaled: (280, 3)
Shape of X_test_scaled: (120, 3)

X_train_scaled (first 5 rows):


Gender       Age  EstimatedSalary
157       1 -0.842522         0.130156
109       0  0.041758         0.277702
17        1  0.729530        -1.315791
347       0  1.613809         1.103957
24        1  0.827784        -1.404318


X_test_scaled (first 5 rows):


Gender       Age  EstimatedSalary
209       0  0.827784        -1.433827
280       0  2.105076         0.513775
33        0 -0.940775        -0.784626
210       0  1.024290         0.749848
93        0 -0.842522        -1.256772

In [30]:
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
model = LogisticRegression(random_state=42)

# Fit the model to the training data
model.fit(X_train_scaled, y_train)

print("Logistic Regression model fitted successfully.")

Logistic Regression model fitted successfully.


In [32]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Make predictions on the scaled test data
y_pred = model.predict(X_test_scaled)

print("Predictions on X_test_scaled (first 10):\n", y_pred[:10])

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Store metrics in a dictionary
Logistic_model_metrics = {
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-Score': f1
}

print("\nModel Evaluation Metrics:")
for metric, value in Logistic_model_metrics.items():
    print(f"{metric}: {value:.4f}")

Predictions on X_test_scaled (first 10):
 [0 1 0 1 0 0 1 0 0 0]

Model Evaluation Metrics:
Accuracy: 0.8583
Precision: 0.9412
Recall: 0.6809
F1-Score: 0.7901


In [42]:
from sklearn.neighbors import KNeighborsClassifier

# Instantiate the KNN classifier
knn_model = KNeighborsClassifier(n_neighbors=7) # You can adjust n_neighbors

# Fit the model to the training data
knn_model.fit(X_train_scaled, y_train)

print("KNN Classifier model fitted successfully.")

KNN Classifier model fitted successfully.


In [43]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
#3-0.8723,5- 0.8936,7-0.9149
# Make predictions on the scaled test data using the KNN model
y_pred_knn = knn_model.predict(X_test_scaled)

print("Predictions on X_test_scaled (first 10) from KNN model:\n", y_pred_knn[:10])

# Calculate evaluation metrics for KNN model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)

# Store metrics in a dictionary
KNN1_model_metrics = {
    'Accuracy': accuracy_knn,
    'Precision': precision_knn,
    'Recall': recall_knn,
    'F1-Score': f1_knn
}

print("\nKNN Model Evaluation Metrics:")
for metric, value in KNN1_model_metrics.items():
    print(f"{metric}: {value:.4f}")

Predictions on X_test_scaled (first 10) from KNN model:
 [1 1 0 1 0 0 1 0 0 0]

KNN Model Evaluation Metrics:
Accuracy: 0.9250
Precision: 0.8958
Recall: 0.9149
F1-Score: 0.9053


In [56]:
from sklearn.svm import SVC

# Instantiate the SVM classifier
svm_model = SVC(kernel='rbf', random_state=42) # You can adjust the kernel and other parameters

# Fit the model to the training data
svm_model.fit(X_train_scaled, y_train)

print("SVM Classifier model fitted successfully.")

SVM Classifier model fitted successfully.


In [57]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
#Recall: ploy- 0.7234 ,rbf- 0.9362
# Make predictions on the scaled test data using the SVM model
y_pred_svm = svm_model.predict(X_test_scaled)

print("Predictions on X_test_scaled (first 10) from SVM model:\n", y_pred_svm[:10])

# Calculate evaluation metrics for SVM model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm)
recall_svm = recall_score(y_test, y_pred_svm)
f1_svm = f1_score(y_test, y_pred_svm)

# Store metrics in a dictionary
SVM_model_metrics = {
    'Accuracy': accuracy_svm,
    'Precision': precision_svm,
    'Recall': recall_svm,
    'F1-Score': f1_svm
}

print("\nSVM Model Evaluation Metrics:")
for metric, value in SVM_model_metrics.items():
    print(f"{metric}: {value:.4f}")

Predictions on X_test_scaled (first 10) from SVM model:
 [1 1 0 1 0 0 1 0 0 0]

SVM Model Evaluation Metrics:
Accuracy: 0.9333
Precision: 0.8980
Recall: 0.9362
F1-Score: 0.9167


In [58]:
import pandas as pd

# Prepare data for the DataFrame
model_summary = [
    {'Model': 'Logistic Regression', 'Test Accuracy': Logistic_model_metrics['Accuracy'], 'Test Precision': Logistic_model_metrics['Precision'], 'Test Recall': Logistic_model_metrics['Recall'], 'Test F1-Score': Logistic_model_metrics['F1-Score']},
    {'Model': 'KNN', 'Test Accuracy': KNN1_model_metrics['Accuracy'], 'Test Precision': KNN1_model_metrics['Precision'], 'Test Recall': KNN1_model_metrics['Recall'], 'Test F1-Score': KNN1_model_metrics['F1-Score']},
    {'Model': 'SVM', 'Test Accuracy': SVM_model_metrics['Accuracy'], 'Test Precision': SVM_model_metrics['Precision'], 'Test Recall': SVM_model_metrics['Recall'], 'Test F1-Score': SVM_model_metrics['F1-Score']}
]

# Create the DataFrame
summary_df = pd.DataFrame(model_summary)

display(summary_df)

Model  Test Accuracy  Test Precision  Test Recall  \
0  Logistic Regression       0.858333        0.941176     0.680851   
1                  KNN       0.925000        0.895833     0.914894   
2                  SVM       0.933333        0.897959     0.936170   

   Test F1-Score  
0       0.790123  
1       0.905263  
2       0.916667

In [59]:
#we want to reduce false negatives, so recall score is mostly used to evaluate